'use strict';
const NX=2720,NY=3120,KEY='remont.constructor.v1',NS='http://www.w3.org/2000/svg';
const $=id=>document.getElementById(id),copy=x=>JSON.parse(JSON.stringify(x));
const names={bed:'Ліжко',desk:'Стіл',storage:'Тумба',tv:'ТВ',door:'Двері'};
const colors={bed:['#e7d3ae','#967954'],desk:['#bfd5df','#527989'],storage:['#d8ccb8','#8c7a60'],tv:['#405365','#405365']};
const conv={x0:0,y0:0,x1:250,y1:750};
let state={layout:null,preset:'concept-02',selected:'bed',buffer:300,snap:true,zones:true,zoom:1,isoTurn:0},history=[],index=-1,saved=[],drag=null,toastTimer;
function toast(t){$('toast').textContent=t;$('toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.display='none',3500)}
function box(x0,y0,x1,y1){return{x0,y0,x1,y1}}
function distance(a,b){return Math.hypot(Math.max(a.x0-b.x1,b.x0-a.x1,0),Math.max(a.y0-b.y1,b.y0-a.y1,0))}
function validLayout(l){if(!l||typeof l!=='object')throw Error('Немає геометрії плану');for(const k of ['bed','desk','storage','tv']){const r=l[k];if(!r||!['x0','y0','x1','y1'].every(n=>Number.isFinite(r[n])))throw Error('Некоректні координати: '+names[k]);if(r.x1<=r.x0||r.y1<=r.y0||r.x1-r.x0>NX||r.y1-r.y0>NY||Math.abs(r.x0)>10000||Math.abs(r.y0)>10000)throw Error('Некоректні габарити: '+names[k])}if(!['x0','x1','y0','y1'].includes(l.bed.head_end))throw Error('Невідоме узголів’я');if(!['-X','+X','-Y','+Y'].includes(l.desk.work_side))throw Error('Невідомий робочий бік стола');if(!l.door||!Number.isFinite(l.door.d_mm)||l.door.d_mm<250||l.door.d_mm>1970||!['InLeft','InRight','OutLeft','OutRight'].includes(l.door.swing))throw Error('Некоректні двері');return true}
function derive(){const l=state.layout,d=l.desk,c=650,p=550,side=d.work_side;let off=Number.isFinite(d.chair_offset_mm)?d.chair_offset_mm:0;const edge=side.endsWith('X')?d.y1-d.y0:d.x1-d.x0;off=Math.max(0,Math.min(off,Math.max(0,edge-c)));let w,r;if(side==='+X'){w=box(d.x1,d.y0+off,d.x1+c,d.y0+off+c);r=box(w.x0+p,w.y0,w.x1+p,w.y1)}else if(side==='-X'){w=box(d.x0-c,d.y0+off,d.x0,d.y0+off+c);r=box(w.x0-p,w.y0,w.x1-p,w.y1)}else if(side==='+Y'){w=box(d.x0+off,d.y1,d.x0+off+c,d.y1+c);r=box(w.x0,w.y0+p,w.x1,w.y1+p)}else{w=box(d.x0+off,d.y0-c,d.x0+off+c,d.y0);r=box(w.x0,w.y0-p,w.x1,w.y1-p)}l.chair_work=w;l.chair_pulled=r;l.chair_swept=box(Math.min(w.x0,r.x0),Math.min(w.y0,r.y0),Math.max(w.x1,r.x1),Math.max(w.y1,r.y1));const pos=l.door.d_mm;l.door.rough=box(NX,pos,NX+100,pos+900);const dd=rotateDoor4ways(l.door,l.door.swing,{nx:NX,ny:NY});Object.assign(l.door,dd,computeDoorSwingGeo(dd.hinge_mm,800,dd.swing,dd.rough));l.door.clear_portal=box(NX,pos+75,NX+100,pos+825);delete l.route;delete l.chair_route;delete l.checks;delete l.clearances_mm;delete l.landing_zone;delete l.door_swing_bbox_bed_gap_mm;delete l.status_note;delete l.headboard_niche_plane_overlap_mm;delete l.assumptions;delete l.concept;delete l.family_ua;delete l.family_key;l.bed.dims_mm=[l.bed.x1-l.bed.x0,l.bed.y1-l.bed.y0];delete l.bed.head_wall_ua;delete l.bed.long_side_used;delete l.desk.work_edge;l.door.return_balcony_mm=pos;l.door.return_blind_mm=NY-pos-900;delete l.door.swing_ua;for(const k of ['wall','wall_ua','view_direction','niche_plane_overlap_mm'])delete l.tv[k];l.status='user_edited_not_route_validated'}
function headTouches(b){return Math.abs(b[b.head_end]-(b.head_end.endsWith('1')?(b.head_end[0]==='x'?NX:NY):0))<1}
function nightAtHead(b,n){let along,adj;if(b.head_end[0]==='x'){const a=b.head_end==='x0'?b.x0:b.x1-400;along=Math.min(n.x1,a+400)>Math.max(n.x0,a);adj=(n.y1<=b.y0+1&&b.y0-n.y1<=150)||(n.y0>=b.y1-1&&n.y0-b.y1<=150)}else{const a=b.head_end==='y0'?b.y0:b.y1-400;along=Math.min(n.y1,a+400)>Math.max(n.y0,a);adj=(n.x1<=b.x0+1&&b.x0-n.x1<=150)||(n.x0>=b.x1-1&&n.x0-b.x1<=150)}return along&&adj}
function checks(){const l=state.layout,w=[],bad=new Set(),keys=['bed','desk','storage','tv'];function add(t,ids=[]){w.push(t);ids.forEach(x=>bad.add(x))}for(let i=0;i<keys.length;i++){const k=keys[i],a=l[k];if(a.x0<-.01||a.y0<-.01||a.x1>NX+.01||a.y1>NY+.01)add(names[k]+' виходить за межі кімнати',[k]);for(const k2 of keys.slice(i+1))if(rectOverlap(a,l[k2]))add(names[k]+' перетинає '+names[k2].toLowerCase(),[k,k2]);if(distance(a,conv)<state.buffer-.01)add(names[k]+': у буфері конвектора',[k]);if(k!=='desk'&&rectOverlap(a,l.chair_swept))add(names[k]+': заважає відсуванню крісла',[k]);if(rectOverlap(a,l.door.swing_zone))add(names[k]+': у межах габариту дуги дверей (консервативно)',[k,'door']);if(a.x1>=NX-.01&&Math.min(a.y1,l.door.rough.y1)>Math.max(a.y0,l.door.rough.y0))add(names[k]+': біля дверного прорізу',[k,'door'])}const s=l.chair_swept;if(s.x0<0||s.y0<0||s.x1>NX||s.y1>NY)add('Кріслу бракує місця для повного відсування',['desk']);if(distance(s,conv)<state.buffer)add('Зона крісла потрапляє в буфер конвектора',['desk']);if(rectOverlap(s,l.door.swing_zone))add('Двері можуть заважати кріслу (габарит дуги)',['door','desk']);if(!headTouches(l.bed))add('Узголів’я не впритул до стіни',['bed']);if(!nightAtHead(l.bed,l.storage))add('Тумба має стояти збоку біля голови',['storage']);const t=l.tv;if(Math.min(Math.abs(t.x0),Math.abs(t.y0),Math.abs(NX-t.x1),Math.abs(NY-t.y1))>1)add('ТВ не розміщено біля стіни',['tv']);if(t.x0<1&&Math.min(t.y1,3060)>Math.max(t.y0,2710))add('ТВ перекриває мале вікно',['tv']);for(const g of [box(2820,0,3700,880),box(3700,2200,4300,3120)])if(rectOverlap(l.door.swing_zone,g))add('Дуга дверей зачіпає відому зовнішню зону',['door']);return{warnings:[...new Set(w)],bad:[...bad],bedDistance:distance(l.bed,conv)}}
function snapshot(){return{layout:copy(state.layout),preset:state.preset,buffer:state.buffer}}
function persist(){try{localStorage.setItem(KEY,JSON.stringify({version:1,...snapshot(),snap:state.snap,zones:state.zones,isoTurn:state.isoTurn,saved}));$('saveStatus').textContent='Збережено в цьому браузері · JSON для перенесення'}catch{$('saveStatus').textContent='Автозбереження недоступне - експортуй JSON'}}
function commit(){derive();history=history.slice(0,index+1);history.push(snapshot());if(history.length>80)history.shift();index=history.length-1;persist();render()}
function restore(n){if(n<0||n>=history.length)return;index=n;Object.assign(state,copy(history[n]));derive();persist();render()}
function loadPreset(id){if(!PRESETS[id])return;state.layout=copy(PRESETS[id]);state.preset=id;commit()}
function moveRect(k,x,y){const a=state.layout[k],w=a.x1-a.x0,h=a.y1-a.y0;let r=box(x,y,x+w,y+h);if(state.snap){r.x0=Math.round(r.x0/50)*50;r.y0=Math.round(r.y0/50)*50;r.x1=r.x0+w;r.y1=r.y0+h}if(Math.abs(r.x0)<35){r.x0=0;r.x1=w}else if(Math.abs(NX-r.x1)<35){r.x0=NX-w;r.x1=NX}if(Math.abs(r.y0)<35){r.y0=0;r.y1=h}else if(Math.abs(NY-r.y1)<35){r.y0=NY-h;r.y1=NY}Object.assign(a,clampRect(r,{nx:NX,ny:NY}))}
function rotateSelected(){const k=state.selected;if(k==='door'){state.layout.door.swing=(state.layout.door.swing.startsWith('In')?'Out':'In')+(state.layout.door.swing.endsWith('Left')?'Left':'Right');commit();return}const a=state.layout[k],w=a.x1-a.x0,h=a.y1-a.y0;if(h>NX||w>NY){toast('Після повороту предмет не вміститься');return}const cx=(a.x0+a.x1)/2,cy=(a.y0+a.y1)/2;Object.assign(a,clampRect(box(cx-h/2,cy-w/2,cx+h/2,cy+w/2),{nx:NX,ny:NY}));if(k==='bed'){const arr=['x0','y0','x1','y1'];a.head_end=arr[(arr.indexOf(a.head_end)+1)%4]}if(k==='desk'){const arr=['-X','-Y','+X','+Y'];a.work_side=arr[(arr.indexOf(a.work_side)+1)%4]}commit()}
const esc=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function svgRect(r,fill,stroke='none',extra=''){return`<rect x="${NX-r.x1}" y="${r.y0}" width="${r.x1-r.x0}" height="${r.y1-r.y0}" fill="${fill}" stroke="${stroke}" ${extra}/>`}
function text(x,y,t,size=55,color='#4d585f',extra=''){size=Math.max(65,size);return`<text x="${x}" y="${y}" text-anchor="middle" font-size="${size}" fill="${color}" font-family="Fixel Text,Segoe UI,sans-serif" ${extra}>${esc(t)}</text>`}
function line(x1,y1,x2,y2,stroke='#636e72',width=10,extra=''){return`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${stroke}" stroke-width="${width}" ${extra}/>`}
function renderPlan(report){const l=state.layout,svg=$('plan'),view=[-1100,-280,4150,3770],cx=view[0]+view[2]/2,cy=view[1]+view[3]/2;svg.setAttribute('viewBox',`${cx-view[2]/state.zoom/2} ${cy-view[3]/state.zoom/2} ${view[2]/state.zoom} ${view[3]/state.zoom}`);let out=`<defs><pattern id="grid" width="100" height="100" patternUnits="userSpaceOnUse"><path d="M100 0H0V100" fill="none" stroke="#e3e6e5" stroke-width="2"/></pattern><clipPath id="roomClip"><rect width="${NX}" height="${NY}"/></clipPath></defs><rect width="${NX}" height="${NY}" fill="#fafbf8"/><rect width="${NX}" height="${NY}" fill="url(#grid)"/>`;out+=svgRect(box(2820,0,3700,880),'#dce5e7','#a0afb5','stroke-width="6" stroke-dasharray="20 15"')+text(-540,380,'До балкона',48)+text(-540,460,'поза спальнею',40);out+=text(1360,-170,'272 см',68)+text(2860,1550,'312 см',60,'#657276','transform="rotate(90 2860 1550)"')+text(2070,-50,'Балконна стіна',45)+text(1360,3270,'Глуха стіна',52);if(state.zones){const b=state.buffer;out+=`<g clip-path="url(#roomClip)">${svgRect(box(-b,-b,250+b,750+b),'#f4e3d7','#d5a287',`rx="${b}" stroke-width="5"`)}</g>`+svgRect(l.chair_swept,'#e6ecef','#9aadb7','stroke-width="5" stroke-dasharray="20 15"')+svgRect(l.chair_work,'#d4e0e5','#819aa8','stroke-width="5"');const cc=l.chair_work;out+=text(NX-(cc.x0+cc.x1)/2,(cc.y0+cc.y1)/2,'Крісло',48)+text(NX-(cc.x0+cc.x1)/2,(cc.y0+cc.y1)/2+75,'+ 55 см',35)}out+=svgRect(conv,'#dfa98d','#a9785e','stroke-width="6" data-fixed="convector"')+text(NX-125,380,'Конвектор',42,'#704b39',`transform="rotate(-90 ${NX-125} 380)"`);out+=line(0,0,NX,0)+line(NX,0,NX,2710)+line(NX,3060,NX,NY)+line(0,NY,NX,NY)+line(NX,2710,NX,3060,'#6cabc3',28)+line(0,0,NX-1340,0,'#a38860',28);out+=text(NX+150,2920,'Вікно',43);out+=svgRect(box(NX,0,NX+100,l.door.d_mm),'#8a969b')+svgRect(box(NX,l.door.d_mm+900,NX+100,NY),'#8a969b');
for(const k of ['bed','desk','storage','tv']){const a=l[k],selected=k===state.selected,bad=report.bad.includes(k),[fill,stroke]=colors[k],cx=NX-(a.x0+a.x1)/2,cy=(a.y0+a.y1)/2;out+=`<g data-item="${k}" tabindex="0" aria-label="${names[k]}">`+svgRect(a,fill,bad?'#bd5d59':selected?'#9064bd':stroke,`stroke-width="${selected?14:7}"`);if(k==='bed'){let h;if(a.head_end==='x0')h=box(a.x0+22,a.y0+70,a.x0+250,a.y1-70);if(a.head_end==='x1')h=box(a.x1-250,a.y0+70,a.x1-22,a.y1-70);if(a.head_end==='y0')h=box(a.x0+70,a.y0+22,a.x1-70,a.y0+250);if(a.head_end==='y1')h=box(a.x0+70,a.y1-250,a.x1-70,a.y1-22);out+=svgRect(h,'#fbf3e4','#b9a27a','rx="45" stroke-width="5"');out+=text(cx,cy-20,'Ліжко',83,'#634f39')+text(cx,cy+80,`${Math.round((a.x1-a.x0)/10)} × ${Math.round((a.y1-a.y0)/10)} см`,58,'#634f39')}else if(k==='tv'){const vertical=a.y1-a.y0>a.x1-a.x0;out+=text(cx,cy+18,'ТВ',44,'white',vertical?`transform="rotate(-90 ${cx} ${cy})"`:'')}else out+=text(cx,cy-10,names[k],k==='storage'?49:65)+text(cx,cy+66,`${Math.round((a.x1-a.x0)/10)} × ${Math.round((a.y1-a.y0)/10)}`,44);out+='</g>'}
const d=l.door,h=d.hinge_mm,o=d.leaf_open,c=d.leaf_closed,top=d.swing.endsWith('Left'),outward=d.swing.startsWith('Out'),start={x:h[0],y:h[1]+(top?800:-800)},end={x:h[0]+(outward?800:-800),y:h[1]},flag=outward===top?1:0;
out+=`<g data-item="door" tabindex="0" aria-label="Двері">${svgRect(d.rough,'transparent','transparent','stroke-width="15"')}${line(NX-start.x,start.y,NX-h[0],h[1],'#97a1a5',5,'stroke-dasharray="20 15"')}<path d="M${NX-start.x} ${start.y} A800 800 0 0 ${flag} ${NX-end.x} ${end.y}" fill="none" stroke="${state.selected==='door'?'#9064bd':'#83939f'}" stroke-width="8"/>${svgRect(o,'#778696',report.bad.includes('door')?'#bd5d59':'#52697a','stroke-width="7"')}<circle cx="${NX-h[0]}" cy="${h[1]}" r="20" fill="#586c7d"/></g>`;svg.innerHTML=out;$('zoomLabel').textContent=Math.round(state.zoom*100)+'%'}

const ROOM={nx:NX,ny:NY},WALL=2500,WALL_T=60;
const ISO_FILL={bed:['#e7d3ae','#cbb188','#ad9670'],desk:['#bfd5df','#9db6c2','#83a0ae'],storage:['#d8ccb8','#b8ab96','#9c8f7c'],tv:['#3e4a57','#5b6773','#4c5762'],door:['#93a0ac','#74828f','#5f6c78'],conv:['#dfa98d','#c28e74','#a87a62'],headboard:['#f6ecd8','#d8c9a9','#bdae90']};
// Shell openings come from the validated model; the door is the only moving one.
let isoBounds=null;
function isoTrack(pts){for(const p of pts){if(!isoBounds)isoBounds={minX:p.sx,maxX:p.sx,minY:p.sy,maxY:p.sy};else{isoBounds.minX=Math.min(isoBounds.minX,p.sx);isoBounds.maxX=Math.max(isoBounds.maxX,p.sx);isoBounds.minY=Math.min(isoBounds.minY,p.sy);isoBounds.maxY=Math.max(isoBounds.maxY,p.sy)}}}
function isoPoly(points,fill,extra=''){isoTrack(points);return`<polygon points="${points.map(p=>p.sx.toFixed(1)+','+p.sy.toFixed(1)).join(' ')}" fill="${fill}" stroke="#15161a" stroke-width="6" stroke-linejoin="round" ${extra}/>`}
function isoSolid(rect,height,base,fill,turns,selected,key){const b=isoBoxFaces(rect,height,base||0,turns,ROOM),tag=key?` data-solid="${key}"`:'';let out='';b.sides.forEach((f,i)=>{out+=isoPoly(f.points,fill[i===0?1:2],tag)});out+=isoPoly(b.top.points,fill[0],tag+(selected?' stroke="#c3a1ea" stroke-width="15"':''));return out}
function wallRect(side,from,to){return side==='top'?{x0:from,y0:0,x1:to,y1:WALL_T}:side==='bottom'?{x0:from,y0:NY-WALL_T,x1:to,y1:NY}:side==='left'?{x0:0,y0:from,x1:WALL_T,y1:to}:{x0:NX-WALL_T,y0:from,x1:NX,y1:to}}
function wallSpan(side){return side==='top'||side==='bottom'?{from:0,to:NX}:{from:0,to:NY}}
function drawWall(side,turns,openings){const span=wallSpan(side);let out='';
 for(const p of isoWallPanels({...span,height:WALL},openings||[]))out+=isoSolid(wallRect(side,p.from,p.to),p.z1-p.z0,p.z0,['#c6c9d0','#b4b8c1','#a3a7b1'],turns,false,null).replace(/data-solid="[^"]*"/g,'')
 return out}
function wallDepth(side,turns){const r=isoRotateRect(wallRect(side,...Object.values(wallSpan(side))),turns,ROOM);return (NX-r.x0)+r.y1}
function renderIso(){const svg=$('iso');if(!svg)return;const l=state.layout,turns=state.isoTurn|0;isoBounds=null;
 const doorHole=[{from:l.door.d_mm,to:l.door.d_mm+900,z0:0,z1:2100,kind:'door'}];
 const sides=[{side:'top',op:ROOM_SHELL.openings.top},{side:'left',op:ROOM_SHELL.openings.left},{side:'bottom',op:ROOM_SHELL.openings.bottom},{side:'right',op:doorHole}]
   .map(w=>({...w,depth:wallDepth(w.side,turns)})).sort((a,b)=>a.depth-b.depth);
 let out=isoPoly(isoBoxFaces({x0:0,y0:0,x1:NX,y1:NY},0,0,turns,ROOM).top.points,'#e9e8e3','stroke="#2a2c32" stroke-width="8"');
 for(const w of sides.slice(0,2))out+=`<g data-wall="${w.side}">${drawWall(w.side,turns,w.op)}</g>`;
  const drawn=sides.slice(0,2).map(w=>w.side);
 // Recesses are shallow pockets in a wall: show them only while that wall is on screen.
 for(const rc of ROOM_SHELL.recesses)if(drawn.includes(rc.side))
  out+=isoSolid(wallRect(rc.side,rc.from,rc.to),rc.z1-rc.z0,rc.z0,['#aeb2bb','#9da1aa','#8d919a'],turns,false,'niche').replace(/data-solid="niche"/g,'data-recess="niche"');
 const shellOps=[{side:'left',...(ROOM_SHELL.openings.left[0]||{}),t:'window',f:['#cfe6f1','#b4d3e2','#9dc2d4']},{side:'right',from:l.door.d_mm,to:l.door.d_mm+900,z0:0,z1:2100,t:'doorway',f:'#9aa2ac'}];
 for(const g of shellOps){if(!drawn.includes(g.side)||!g.from&&g.from!==0)continue;
  for(const face of isoOpeningReveal(g,WALL_T,turns,ROOM))out+=isoPoly(face.points,g.f,`data-opening="${g.t}"`)}
 // A wall-mounted item keeps a backing strip even when its wall is culled, so it never floats.
 const tvWall=l.tv.y1<=NY/2?'top':l.tv.y0>=NY/2?'bottom':l.tv.x1<=NX/2?'left':'right';
 const tvBack=tvWall==='top'?{x0:l.tv.x0-120,y0:0,x1:l.tv.x1+120,y1:WALL_T}:tvWall==='bottom'?{x0:l.tv.x0-120,y0:NY-WALL_T,x1:l.tv.x1+120,y1:NY}:tvWall==='left'?{x0:0,y0:l.tv.y0-120,x1:WALL_T,y1:l.tv.y1+120}:{x0:NX-WALL_T,y0:l.tv.y0-120,x1:NX,y1:l.tv.y1+120};
 const clampRectRoom=r=>({x0:Math.max(0,r.x0),y0:Math.max(0,r.y0),x1:Math.min(NX,r.x1),y1:Math.min(NY,r.y1)});
 // A screen on a culled near wall would hang between the viewer and the room: omit it for that corner.
 const drawnWalls=sides.slice(0,2).map(w=>w.side),showTv=drawnWalls.includes(tvWall);
 const items=[{key:'conv',rect:conv},{key:'bed',rect:l.bed},{key:'desk',rect:l.desk},{key:'storage',rect:l.storage},{key:'door',rect:l.door.leaf_open}];
 if(showTv)items.push({key:'tv',rect:l.tv});
 for(const it of isoDepthSort(items,turns,ROOM)){
  const h=FURNITURE_HEIGHT[it.key]||{height:400,base:0};
  if(it.key==='tv')out+=isoSolid(clampRectRoom(tvBack),FURNITURE_HEIGHT.tv.base+FURNITURE_HEIGHT.tv.height+150,0,['#bcc0c8','#aaaeb7','#9a9ea8'],turns,false,'tvback').replace(/data-solid="tvback"/g,'data-backing="tv"');
  out+=isoSolid(it.rect,h.height,h.base,ISO_FILL[it.key],turns,it.key===state.selected,it.key);
  if(it.key==='bed'){const b=l.bed,hd=b.head_end==='x0'?{x0:b.x0,y0:b.y0,x1:b.x0+120,y1:b.y1}:b.head_end==='x1'?{x0:b.x1-120,y0:b.y0,x1:b.x1,y1:b.y1}:b.head_end==='y0'?{x0:b.x0,y0:b.y0,x1:b.x1,y1:b.y0+120}:{x0:b.x0,y0:b.y1-120,x1:b.x1,y1:b.y1};
   out+=isoSolid(hd,900,0,ISO_FILL.headboard,turns,false,'headboard')}}
 svg.innerHTML=out;
 const pad=140,b=isoBounds||{minX:-1,maxX:1,minY:-1,maxY:1};
 svg.setAttribute('viewBox',`${b.minX-pad} ${b.minY-pad} ${b.maxX-b.minX+pad*2} ${b.maxY-b.minY+pad*2}`);
 $('isoAngle').textContent='кут '+(turns+1)+' з 4';
}
$('isoRotateLeft').onclick=()=>{state.isoTurn=((state.isoTurn|0)+3)%4;persist();renderIso()};
$('isoRotateRight').onclick=()=>{state.isoTurn=((state.isoTurn|0)+1)%4;persist();renderIso()};
function render(){const report=checks();renderPlan(report);renderIso();$('preset').value=state.preset;document.querySelectorAll('[data-select]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.select===state.selected));$('selectedTitle').textContent=names[state.selected];const isDoor=state.selected==='door';$('furnitureFields').classList.toggle('hide',isDoor);$('doorFields').classList.toggle('hide',!isDoor);function val(id,n){if(document.activeElement!==$(id))$(id).value=n}if(!isDoor){const a=state.layout[state.selected];val('posX',+( (NX-a.x1)/10).toFixed(1));val('posY',+(a.y0/10).toFixed(1));val('sizeX',+((a.x1-a.x0)/10).toFixed(1));val('sizeY',+((a.y1-a.y0)/10).toFixed(1));const label={x0:'праворуч',x1:'ліворуч',y0:'угорі',y1:'унизу','-X':'праворуч','+X':'ліворуч','-Y':'угорі','+Y':'унизу'};$('orientation').textContent=state.selected==='bed'?'Узголів’я '+label[a.head_end]:state.selected==='desk'?'Крісло '+label[a.work_side]+'. Зона рухається разом зі столом.':'Розміри на плані, не висота предмета.'}val('doorPos',state.layout.door.d_mm/10);val('doorSlide',state.layout.door.d_mm/10);val('doorDirection',state.layout.door.swing.startsWith('In')?'In':'Out');val('doorHinge',state.layout.door.swing.endsWith('Left')?'Left':'Right');val('buffer',state.buffer/10);$('bedDistance').textContent=(report.bedDistance/10).toFixed(1)+' см';$('checks').replaceChildren();for(const w of report.warnings){const li=document.createElement('li');li.textContent=w;$('checks').append(li)}if(!report.warnings.length){const li=document.createElement('li');li.className='ok';li.textContent='Перевірені перетини не виявлені. Прохід ще не перевірено.';$('checks').append(li)}$('undo').disabled=index<=0;$('redo').disabled=index>=history.length-1;$('snap').checked=state.snap;$('zones').checked=state.zones}
function svgPoint(e){return new DOMPoint(e.clientX,e.clientY).matrixTransform($('plan').getScreenCTM().inverse())}
$('plan').addEventListener('pointerdown',e=>{const target=e.target.closest('[data-item]');if(!target||e.button!==0)return;e.preventDefault();state.selected=target.dataset.item;drag={key:state.selected,p:svgPoint(e),layout:copy(state.layout),before:JSON.stringify(state.layout),pointer:e.pointerId};$('plan').setPointerCapture(e.pointerId);render()});
$('plan').addEventListener('pointermove',e=>{if(!drag||drag.pointer!==e.pointerId)return;const p=svgPoint(e),dx=p.x-drag.p.x,dy=p.y-drag.p.y,k=drag.key;state.layout=copy(drag.layout);if(k==='door'){let n=drag.layout.door.d_mm+dy;if(state.snap)n=Math.round(n/50)*50;state.layout.door.d_mm=Math.max(250,Math.min(1970,n))}else moveRect(k,drag.layout[k].x0-dx,drag.layout[k].y0+dy);derive();render()});
$('plan').addEventListener('pointerup',e=>{if(!drag)return;const changed=JSON.stringify(state.layout)!==drag.before;drag=null;if($('plan').hasPointerCapture(e.pointerId))$('plan').releasePointerCapture(e.pointerId);if(changed)commit();else render()});$('plan').addEventListener('pointercancel',()=>{if(drag){state.layout=drag.layout;drag=null;derive();render()}});
document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{state.selected=b.dataset.select;render()});$('rotate').onclick=rotateSelected;$('undo').onclick=()=>restore(index-1);$('redo').onclick=()=>restore(index+1);$('preset').onchange=e=>loadPreset(e.target.value);$('reset').onclick=()=>{if(confirm('Скинути поточний план до початкового пресета? Збережені варіанти залишаться.'))loadPreset(state.preset)};
for(const id of ['posX','posY','sizeX','sizeY'])$(id).onchange=()=>{const n=Number($(id).value)*10,k=state.selected;if(k==='door')return;const a=state.layout[k],w=a.x1-a.x0,h=a.y1-a.y0;if(!Number.isFinite(n)||((id==='sizeX'||id==='sizeY')&&n<=0)||(id==='sizeX'&&n>NX)||(id==='sizeY'&&n>NY)){toast('Введи коректний розмір у сантиметрах');render();return}if(id==='posX')Object.assign(a,clampRect(box(NX-n-w,a.y0,NX-n,a.y1),{nx:NX,ny:NY}));if(id==='posY')Object.assign(a,clampRect(box(a.x0,n,a.x1,n+h),{nx:NX,ny:NY}));if(id==='sizeX')Object.assign(a,clampRect(box(a.x1-n,a.y0,a.x1,a.y1),{nx:NX,ny:NY}));if(id==='sizeY')Object.assign(a,clampRect(box(a.x0,a.y0,a.x1,a.y0+n),{nx:NX,ny:NY}));commit()};
for(const id of ['doorPos','doorSlide','doorDirection','doorHinge'])$(id).onchange=()=>{let d=Number($('doorPos').value)*10;if(id==='doorSlide')d=Number($('doorSlide').value)*10;if(!Number.isFinite(d))return;state.layout.door.d_mm=Math.max(250,Math.min(1970,d));state.layout.door.swing=$('doorDirection').value+$('doorHinge').value;commit()};$('buffer').onchange=()=>{const n=Number($('buffer').value);if(!Number.isFinite(n))return;state.buffer=Math.max(0,Math.min(1500,n*10));commit()};$('snap').onchange=()=>{state.snap=$('snap').checked;persist()};$('zones').onchange=()=>{state.zones=$('zones').checked;persist();render()};$('zoomIn').onclick=()=>{state.zoom=Math.min(3,state.zoom*1.2);render()};$('zoomOut').onclick=()=>{state.zoom=Math.max(.5,state.zoom/1.2);render()};$('fit').onclick=()=>{state.zoom=1;render()};
document.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||e.target.isContentEditable)return;const ctrl=e.ctrlKey||e.metaKey;if(ctrl&&e.key.toLowerCase()==='z'){e.preventDefault();restore(index+(e.shiftKey?1:-1));return}if(ctrl&&e.key.toLowerCase()==='y'){e.preventDefault();restore(index+1);return}if(!ctrl&&e.code==='KeyR'){e.preventDefault();rotateSelected();return}if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const n=e.shiftKey?100:10,k=state.selected,dx=e.key==='ArrowLeft'?n:e.key==='ArrowRight'?-n:0,dy=e.key==='ArrowUp'?-n:e.key==='ArrowDown'?n:0;if(k==='door'){state.layout.door.d_mm=Math.max(250,Math.min(1970,state.layout.door.d_mm+dy))}else{const a=state.layout[k];Object.assign(a,clampRect(box(a.x0+dx,a.y0+dy,a.x1+dx,a.y1+dy),{nx:NX,ny:NY}))}commit()});
function download(name,body,type){const url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function exportData(){return{format:'remont-room-v1',room:{nx:NX,ny:NY},layout:copy(state.layout),buffer:state.buffer,notice:'Ручний план. Перетини не доводять прохідність або теплову безпеку.'}}
$('exportJSON').onclick=()=>download('my-room-plan.json',JSON.stringify(exportData(),null,2),'application/json');$('exportSVG').onclick=()=>{const clone=$('plan').cloneNode(true);clone.setAttribute('xmlns',NS);clone.setAttribute('viewBox','-1100 -280 4150 3770');clone.setAttribute('width','1500');clone.setAttribute('height','1363');download('my-room-plan.svg',new XMLSerializer().serializeToString(clone),'image/svg+xml')};$('importJSON').onclick=()=>$('fileInput').click();function importData(data){const l=copy(data.layout||data);validLayout(l);state.layout=l;if(Number.isFinite(data.buffer))state.buffer=Math.max(0,Math.min(1500,data.buffer));commit()}
$('fileInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>1000000)throw Error('Файл завеликий');importData(JSON.parse(await f.text()));toast('План імпортовано')}catch(err){toast('Не імпортовано: '+err.message)}e.target.value=''};
function renderSaved(){const s=$('savedVariants');s.replaceChildren(new Option('Оберіть варіант',''));saved.forEach((v,i)=>s.add(new Option(v.name,String(i))))}
$('saveVariant').onclick=()=>{const name=$('variantName').value.trim();if(!name){toast('Вкажи назву варіанта');return}if(saved.length>=50){toast('Ліміт 50 варіантів; експортуй або видали зайві');return}saved.push({name:name.slice(0,80),...snapshot()});persist();renderSaved();$('savedVariants').value=String(saved.length-1);toast('Варіант збережено')};$('loadVariant').onclick=()=>{const i=$('savedVariants').value;if(i==='')return;Object.assign(state,copy(saved[Number(i)]));commit();toast('Варіант відкрито')};$('deleteVariant').onclick=()=>{const i=$('savedVariants').value;if(i===''||!confirm('Видалити цей збережений варіант?'))return;saved.splice(Number(i),1);persist();renderSaved()};
state.layout=copy(PRESETS['concept-02']);try{const v=JSON.parse(localStorage.getItem(KEY));if(v&&v.version===1){validLayout(v.layout);state.layout=v.layout;state.preset=PRESETS[v.preset]?v.preset:'concept-02';state.buffer=Number.isFinite(v.buffer)?Math.max(0,Math.min(v.buffer,1500)):300;state.snap=v.snap!==false;state.zones=v.zones!==false;state.isoTurn=[0,1,2,3].includes(v.isoTurn)?v.isoTurn:0;saved=Array.isArray(v.saved)?v.saved.filter(s=>{try{validLayout(s.layout);return typeof s.name==='string'}catch{return false}}).slice(0,50):[]}}catch{}derive();history=[snapshot()];index=0;renderSaved();render();
window.roomEditor={getState:()=>({...snapshot(),selected:state.selected,snap:state.snap,zones:state.zones,isoTurn:state.isoTurn,zoom:state.zoom,historyLength:history.length,historyIndex:index,checks:checks()}),getLayout:()=>copy(state.layout),loadPreset,importData,exportData,checkCollisions:()=>checks(),undo:()=>restore(index-1),redo:()=>restore(index+1)};

